services:
  app-dev:
    container_name: photo_viewer_backend_dev
    build:
      context: .
      dockerfile: Dockerfile.dev  # 開発環境用のDockerfile
    volumes:
      - .:/app  # ホットリロード用にソースコードをコンテナにマウント
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    environment:
      - ENV=development
      - NAS_SERVER_PATH=${NAS_SERVER_PATH}
      - BACKEND_PORT=${BACKEND_PORT}
