version: '3.8'

services:
  app-dev:
    container_name: photo_viewer_backend_dev
    build:
      context: .
      dockerfile: Dockerfile.dev  # 開発環境用のDockerfile
    volumes:
      - .:/app  # ホットリロード用にソースコードをコンテナにマウント
    ports:
      - "8080:8080"
    environment:
      - ENV=development
      - NAS_PATH=${NAS_PATH}
