version: '3.8'

services:
  app-prod:
    container_name: photo_viewer_backend_prod
    build:
      context: .
      dockerfile: Dockerfile.prod  # 本番環境用のDockerfile
    ports:
      - "8080:8080"
    environment:
      - ENV=production
      - NAS_SERVER_PATH=${NAS_SERVER_PATH}
networks:
  webnet:
    external: true
